services:
    app:
        build:
            context: .
        container_name: dormdash-app
        image: dormdash-app:latest
        depends_on:
            db:
                condition: service_healthy
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 5s
            timeout: 5s
            retries: 10
        environment:
            - APP_ENV=local
            - DB_HOST=db
            - DB_DATABASE=dormdash_db_v4
            - DB_USERNAME=root
            - DB_PASSWORD=pass
        entrypoint: ["/bin/sh", "/var/www/docker/maria-db/entrypoint.sh"]
        command: ["php-fpm", "-F"]
        volumes:
            - .:/var/www
        networks:
            - laravel

    nginx:
        image: nginx:alpine
        container_name: dormdash-nginx-laravel
        volumes:
            - .:/var/www
            - ./docker/nginx:/etc/nginx/conf.d
        ports:
            - "8080:80"
        depends_on:
            - app
        networks:
            - laravel

    db:
        image: mysql:8.0
        container_name: dormdash-db
        restart: always
        ports:
            - "3307:3306" #3307 so it doesn't conflict with your host
        environment:
            MYSQL_ROOT_PASSWORD: pass
            MYSQL_DATABASE: dormdash_db_v4
        volumes:
            - dbdata:/var/lib/mysql
            - ./database/init:/docker-entrypoint-initdb.d
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-ppass" ]
            interval: 5s
            timeout: 5s
            retries: 10
        networks:
            - laravel
    node:
        image: node:20-alpine
        container_name: dormdash-node
        working_dir: /var/www
        volumes:
            - .:/var/www
        command: sh -c "npm install && npm run dev"
        ports:
            - "5173:5173"
        networks:
            - laravel
        environment:
            CHOKIDAR_USEPOLLING: "true"
        build:
            context: .
            dockerfile: Dockerfile.node
networks:
    laravel:
        name: laravel
        driver: bridge
        external: false

volumes:
    dbdata:

