version: "3.9"

services:
    app:
        build:
            context: .
        container_name: dormdash-app
        image: dormdash-app:latest
        volumes:
            - .:/var/www
        networks:
            - laravel

    nginx:
        image: nginx:alpine
        container_name: dormdash-nginx-laravel
        volumes:
            - .:/var/www
            - ./docker/nginx:/etc/nginx/conf.d
        ports:
            - "8080:80"
        depends_on:
            - app
        networks:
            - laravel
networks:
    laravel:

